name: Testing

on:
  push:
    branches: [ master, '1.x', '2.x', 'use-mr-linter' ]
  pull_request:
    branches: [ master, '1.x', '2.x' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Lint Pull Request
      uses: mr-linter/mr-linter-ga@v0.1.0
      env:
        MR_LINTER_GITHUB_TOKEN: ${{ secrets.MR_LINTER_GITHUB_TOKEN }}

    - uses: nanasess/setup-php@master
      with:
        php-version: '7.3'

    - name: Validate composer.json
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Lint
      run: composer lint

    - name: Stat Analyse
      run: composer stat-analyse

    - name: Run Tests
      run: composer test
